### ISSUE TITLE
Cannot get certificates for subdomains

### ISSUE THREAD

**Issue by GabrielZirk** [caddy-dns/inwx#9]
Hello module author,

obtaining certificates for my https://domainname.dev works perfectly fine, but I am not able to get them for any subdomain, including https://www.domainname.dev.

This is my Caddyfile:

```
{
    debug
}

domainname.dev, www.domainname.dev {
    root * /usr/share/caddy/public
    file_server

    # Redirect HTTP to HTTPS
    @http {
        protocol http
    }
    redir @http https://{host}{uri} 301

    tls {
        dns inwx {
            username ${INWX_USERNAME}
            password ${INWX_PASSWORD}
        }
    }
}

home.domainname.dev {
    # root * /usr/share/caddy/public
    # file_server

    respond "Hello" 200

    # Redirect HTTP to HTTPS
    @http {
        protocol http
    }
    redir @http https://{host}{uri} 301

    tls {
        dns inwx {
            username ${INWX_USERNAME}
            password ${INWX_PASSWORD}
        }
    }
}
```
This is my Dockerfile:

```
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/inwx

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

And my compose.yml to start my docker docktainer:

```
services:
  caddy:
    image: caddy-inwx
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/usr/share/caddy/public
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - INWX_USERNAME=${CADDY_INWX_USERNAME}
      - INWX_PASSWORD=${CADDY_INWX_PASSWORD}

volumes:
  caddy_data:
  caddy_config:
```
Of course there are A records for www.domainname.dev and home.domainname.dev!

Since I get the certificate for https://domainname.dev, I dont think there is an issue with incorrect credentials and the are properly served by my .env file.

However, there seems to be something wrong with the authentication, see caddy log output below:
```
caddy  | {"level":"error","ts":1729447364.3561056,"logger":"tls.obtain","msg":"will retry","error":"[www.domainname.dev] Obtain: [www.domainname.dev] solving challenges: presenting for challenge: adding temporary record for zone \"domainname.dev.\": (2200) Authentication error (order=https://acme-v02.api.letsencrypt.org/acme/order/2009592577/315493xxx) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":5.068295076,"max_duration":2592000}

```

Any help is appreciated, thanks in advance!
Best
